<?php

namespace ChallengeBundle\Repository;

/**
 * DetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
