<?php

namespace ChallengeBundle\Repository;

/**
 * MaritalStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaritalStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
